package generator

import service "github.com/h3yng/drb99/services"

func (g *Generator) generateCurl(cfg service.WrapperConfig) (map[string]string, error) {
	installSh, err := renderTemplate(curlInstallTemplate, cfg)
	if err != nil {
		return nil, err
	}

	return map[string]string{
		"install.sh": installSh,
	}, nil
}

const curlInstallTemplate = `#!/bin/sh
# Generated by drb99 — curl installer for {{ .BinaryName }}
# https://github.com/h3yng/drb99
# Repo: {{ .RepoURL }}  Version: {{ .Version }}
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/{{ .Owner }}/{{ .Repo }}/main/install.sh | sh
#   curl -fsSL https://raw.githubusercontent.com/{{ .Owner }}/{{ .Repo }}/main/install.sh | sh -s -- --help
#   curl -fsSL https://github.com/{{ .Owner }}/{{ .Repo }}/releases/download/{{ .Version }}/install.sh -o install.sh && sh install.sh
#   BINDIR=$HOME/.local/bin sh install.sh
#   sh install.sh --dir /usr/local/bin
#   # custom URL install (manual mode) — URL is baked into install.sh per-platform
set -e

BINARY_NAME={{ printf "%q" .BinaryName }}
OWNER={{ printf "%q" .Owner }}
REPO={{ printf "%q" .Repo }}
VERSION={{ printf "%q" .Version }}
REPO_URL={{ printf "%q" .RepoURL }}

# allow override via env or flag
BINDIR="${BINDIR:-${INSTALL_DIR:-}}"
VERSION_OVERRIDE="${VERSION:-}"

usage() {
  cat <<'USAGE'
Usage: install.sh [OPTIONS]

Options:
  -d, --dir DIR        Install directory (default: /usr/local/bin or $HOME/.local/bin)
  -v, --version VER    Version to install (default: {{ .Version }})
  -h, --help           Show this help

Env:
  BINDIR / INSTALL_DIR  Same as --dir
  VERSION               Same as --version
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    -d|--dir) BINDIR="$2"; shift 2 ;;
    --dir=*) BINDIR="${1#*=}"; shift ;;
    -v|--version) VERSION_OVERRIDE="$2"; shift 2 ;;
    --version=*) VERSION_OVERRIDE="${1#*=}"; shift ;;
    -h|--help) usage; exit 0 ;;
    --) shift; break ;;
    -*) echo "unknown option: $1" >&2; usage >&2; exit 1 ;;
    *) break ;;
  esac
done

if [ -n "$VERSION_OVERRIDE" ]; then
  VERSION="$VERSION_OVERRIDE"
fi

if [ -z "$VERSION" ]; then
  echo "error: version is empty" >&2
  exit 1
fi

detect_os_arch() {
  OS="$(uname -s 2>/dev/null || echo unknown)"
  ARCH="$(uname -m 2>/dev/null || echo unknown)"

  case "$OS" in
    Linux) OS="linux" ;;
    Darwin) OS="macos" ;;
    FreeBSD) OS="linux" ;;
    *) echo "unsupported OS: $OS (supported: linux, darwin)" >&2; exit 1 ;;
  esac

  case "$ARCH" in
    x86_64|amd64|x64) ARCH="amd64" ;;
    aarch64|arm64|armv8*) ARCH="arm64" ;;
    *) echo "unsupported arch: $ARCH (supported: amd64, arm64)" >&2; exit 1 ;;
  esac

  case "${OS}_${ARCH}" in
    linux_amd64) SUFFIX="linux_amd64" ;;
    linux_arm64) SUFFIX="linux_arm64" ;;
    macos_amd64) SUFFIX="macos_amd64" ;;
    macos_arm64) SUFFIX="macos_arm64" ;;
    *) echo "unsupported platform: ${OS}_${ARCH}" >&2; exit 1 ;;
  esac
}

detect_os_arch

# --- drb99: platform -> asset URL(s) (supports custom naming via asset_urls) ---
# Prefill note: GET /api/v1/prefill returns latest assets; frontend maps them to platforms
# so you can pass custom URLs via asset_urls in manual mode.
case "$SUFFIX" in
{{- range .Platforms }}
  {{ .GoSuffix }})
    # {{ .InputKey }} ({{ .NodeKey }}) -> {{ .BinaryFile }} [{{ .Archive }}]
    URLS={{ printf "%q" (index .URLs 0) }}
    # fallback URLs (if multiple provided)
    FALLBACK_URLS="{{ range $i, $u := .URLs }}{{ if $i }} {{ end }}{{ $u }}{{ end }}"
    ARCHIVE={{ printf "%q" .BinaryFile }}
    ARCHIVE_TYPE={{ printf "%q" .Archive }}
    ;;
{{- end }}
  *) echo "unsupported platform suffix: $SUFFIX" >&2; exit 1 ;;
esac

# backwards compat: if asset URL not baked (empty), construct GitHub URL from naming convention
if [ -z "$URLS" ] || [ "$URLS" = "" ]; then
  ARCHIVE="${BINARY_NAME}_${VERSION}_${SUFFIX}.tar.gz"
  URLS="https://github.com/${OWNER}/${REPO}/releases/download/${VERSION}/${ARCHIVE}"
  FALLBACK_URLS="$URLS"
  ARCHIVE_TYPE="tar.gz"
fi

# support multiple fallback URLs separated by space
# normalize to space-separated list
ALL_URLS="$FALLBACK_URLS"
if [ -z "$ALL_URLS" ]; then
  ALL_URLS="$URLS"
fi

# resolve BINDIR if not given
if [ -z "$BINDIR" ]; then
  if [ -w /usr/local/bin ]; then
    BINDIR="/usr/local/bin"
  elif [ -n "$HOME" ] && [ -d "$HOME" ]; then
    BINDIR="$HOME/.local/bin"
  else
    BINDIR="/usr/local/bin"
  fi
fi

# detect downloader
downloader=""
if command -v curl >/dev/null 2>&1; then
  downloader="curl"
elif command -v wget >/dev/null 2>&1; then
  downloader="wget"
else
  echo "error: curl or wget is required" >&2
  exit 1
fi

TMPDIR="$(mktemp -d 2>/dev/null || mktemp -d -t drb99)"
cleanup() { rm -rf "$TMPDIR"; }
trap cleanup EXIT INT TERM

# download with fallback loop
ARCHIVE_PATH=""
download_success=0
for URL in $ALL_URLS; do
  # derive archive name from URL basename if not set
  _archive_name="$(basename "$URL")"
  if [ -z "$_archive_name" ] || [ "$_archive_name" = "/" ]; then
    _archive_name="$ARCHIVE"
  fi
  ARCHIVE_PATH="$TMPDIR/$_archive_name"
  echo "[drb99] Installing ${BINARY_NAME} ${VERSION} for ${SUFFIX}"
  echo "[drb99] Downloading $URL"
  if [ "$downloader" = "curl" ]; then
    if curl -fsSL "$URL" -o "$ARCHIVE_PATH"; then
      if [ -s "$ARCHIVE_PATH" ]; then
        download_success=1
        break
      fi
    fi
  else
    if wget -qO "$ARCHIVE_PATH" "$URL"; then
      if [ -s "$ARCHIVE_PATH" ]; then
        download_success=1
        break
      fi
    fi
  fi
  echo "[drb99] Download failed from $URL, trying next..." >&2
  rm -f "$ARCHIVE_PATH"
done

if [ "$download_success" != "1" ] || [ ! -s "$ARCHIVE_PATH" ]; then
  echo "error: all downloads failed. Tried: $ALL_URLS" >&2
  exit 1
fi

# detect archive type if not set
if [ -z "$ARCHIVE_TYPE" ]; then
  case "$ARCHIVE_PATH" in
    *.zip) ARCHIVE_TYPE="zip" ;;
    *.tar.gz|*.tgz) ARCHIVE_TYPE="tar.gz" ;;
    *) ARCHIVE_TYPE="tar.gz" ;;
  esac
fi

echo "[drb99] Extracting $(basename "$ARCHIVE_PATH") [$ARCHIVE_TYPE]"

EXTRACT_DIR="$TMPDIR/extract"
mkdir -p "$EXTRACT_DIR"
if [ "$ARCHIVE_TYPE" = "zip" ]; then
  if command -v unzip >/dev/null 2>&1; then
    unzip -q "$ARCHIVE_PATH" -d "$EXTRACT_DIR"
  else
    echo "error: unzip is required for zip archive" >&2
    exit 1
  fi
else
  tar -xzf "$ARCHIVE_PATH" -C "$EXTRACT_DIR"
fi

# find binary (handle binary or binary.exe or nested)
BIN_SRC=""
if [ -f "$EXTRACT_DIR/$BINARY_NAME" ]; then
  BIN_SRC="$EXTRACT_DIR/$BINARY_NAME"
else
  BIN_SRC="$(find "$EXTRACT_DIR" -type f -name "$BINARY_NAME" -print 2>/dev/null | head -n 1)"
  if [ -z "$BIN_SRC" ]; then
    BIN_SRC="$(find "$EXTRACT_DIR" -type f -perm -111 -print 2>/dev/null | head -n 1)"
  fi
  if [ -z "$BIN_SRC" ]; then
    BIN_SRC="$(find "$EXTRACT_DIR" -type f -print 2>/dev/null | head -n 1)"
  fi
fi

if [ -z "$BIN_SRC" ] || [ ! -f "$BIN_SRC" ]; then
  echo "error: could not find binary ${BINARY_NAME} in archive" >&2
  echo "archive contents:" >&2
  ls -R "$EXTRACT_DIR" >&2 || true
  exit 1
fi

mkdir -p "$BINDIR"
BIN_DST="$BINDIR/$BINARY_NAME"

if [ -e "$BIN_DST" ] && [ ! -w "$BIN_DST" ] && [ ! -w "$BINDIR" ]; then
  echo "[drb99] $BIN_DST is not writable, trying with sudo (if available)" >&2
  if command -v sudo >/dev/null 2>&1; then
    sudo mv -f "$BIN_SRC" "$BIN_DST"
    sudo chmod +x "$BIN_DST"
    echo "[drb99] Installed $BIN_DST"
    echo "[drb99] Run: $BINARY_NAME --help"
    exit 0
  fi
fi

mv -f "$BIN_SRC" "$BIN_DST"
chmod +x "$BIN_DST"

echo "[drb99] Installed $BIN_DST"
case ":$PATH:" in
  *":$BINDIR:"*) ;;
  *) echo "[drb99] NOTE: $BINDIR is not in PATH. Add it: export PATH=\"$BINDIR:\$PATH\"" ;;
esac
echo "[drb99] Run: $BINARY_NAME --help"
`
